on: push

name: 🚀 Deploy Laravel API

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Generate Laravel Key
        run: php artisan key:generate

      - name: Generate Storage Link
        run: php artisan storage:link

      - name: Set Directory Permissions
        run: chmod -R 755 storage bootstrap/cache
        
      - name: Remove vendor directory
        run: rm -rf vendor/
    
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          
