name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sync files to cPanel
        run: |
          /usr/bin/docker run --name c2393b837d191033a4300b698e4b66f9d9f9b_5d7e56 --label 6c2393 --workdir /github/workspace --rm -e "INPUT_SERVER=${{ secrets.CPANEL_HOST }}" -e "INPUT_USERNAME=${{ secrets.CPANEL_USERNAME }}" -e "INPUT_PASSWORD=${{ secrets.CPANEL_PASSWORD }}" -e "INPUT_SCRIPT=php artisan deploy" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/phpapi-poc/phpapi-poc":"/github/workspace" 6c2393:b837d191033a4300b698e4b66f9d9f9b
