name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sync files to cPanel
        uses: appleboy/ssh-action@master
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          script: |
            cd /path/to/your/laravel/project

            # Pull the latest changes
            git pull origin main

            # Install/update Composer dependencies
            composer install --no-dev --optimize-autoloader

            # Run database migrations
            php artisan migrate --force

            # Additional commands if needed (e.g., cache clearing)
            php artisan cache:clear
            php artisan config:cache

            # Ensure proper directory permissions
            chmod -R 755 storage bootstrap/cache

            # Restart web server if needed (e.g., Apache or Nginx)
            # systemctl restart apache2

            # Note: Adjust the commands based on your specific deployment needs

